import 'dart:async';
import 'dart:convert';

import 'package:hmpaisrn/data/autogenerated.dart';
import 'package:http/http.dart' as http;

Future<Autogenerated> fetchPeopleInSpace() async {
  final response = await http.get(
      Uri.http('howmanypeopleareinspacerightnow.com', 'peopleinspace.json'));

  if (response.statusCode <= 299) {
    var people =
        Autogenerated.fromJson(json.decode(utf8.decode(response.bodyBytes)));
    return people;
  } else {
    // If that call was not successful, throw an error.
    throw Exception('Failed to load post');
  }
}
