import 'people.dart';

class Autogenerated {
  int number;
  List<People> people;

  Autogenerated({this.number, this.people});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    number = json['number'];
    if (json['people'] != null) {
      people = new List<People>();
      json['people'].forEach((v) {
        people.add(new People.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['number'] = this.number;
    if (this.people != null) {
      data['people'] = this.people.map((v) => v.toJson()).toList();
    }
    return data;
  }
}