import 'package:flutter/material.dart';
import 'widgets/background/index.dart';
import 'package:hmpaisrn/screens/home/widgets/text_number/index.dart';
import 'package:hmpaisrn/data/autogenerated.dart';
import 'dart:async';

class Home extends StatelessWidget {
  final Future<Autogenerated> autogenerated;

  Home({Key key, this.autogenerated}) : super(key: key);

  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return new MaterialApp(
      title: 'How Many People Are In Space Right Now?',
      theme: ThemeData.dark(),
      home: FutureBuilder<Autogenerated>(
        future: autogenerated,
        builder: (context, snapshot) {
          if (snapshot.hasData) {
            return new PeopleNumberPage(
              title: 'How Many People In Space',
              autogeneratedNumber: snapshot.data,
              offline: false,
            );
          } else if (snapshot.hasError) {
            return new PeopleNumberPage(
              title: 'How Many People In Space',
              autogeneratedNumber:
                  new Autogenerated(number: 0, people: List(0)),
              offline: true,
            );
          }
          return new Container();
        },
      ),
    );
  }
}

class PeopleNumberPage extends StatefulWidget {
  final Autogenerated autogeneratedNumber;
  final String title;
  final bool offline;

  PeopleNumberPage(
      {Key key, this.autogeneratedNumber, this.title, this.offline})
      : super(key: key);

  @override
  _PeopleNumberPageState createState() =>
      new _PeopleNumberPageState(autogeneratedNumber, offline);
}

class _PeopleNumberPageState extends State<PeopleNumberPage> {
  final Autogenerated autogeneratedNumber;
  final bool offline;

  _PeopleNumberPageState(this.autogeneratedNumber, this.offline) : super();

  @override
  Widget build(BuildContext context) {
    if (offline) {
      return new Scaffold(
        appBar: new AppBar(
          title: new Text(widget.title),
        ),
        body: Stack(
          children: <Widget>[
            new Background(),
            new TextNumber(
                autogeneratedNumber: 0,
                people: List(0),
                fontSize: 188.0,
                fontColor: Colors.white.withOpacity(0.8),
                offline: true),
          ],
        ),
      );
    } else
      return new Scaffold(
        appBar: new AppBar(
          title: new Text(widget.title),
        ),
        body: Stack(
          children: <Widget>[
            new Background(),
            new TextNumber(
                autogeneratedNumber: this.autogeneratedNumber.number,
                people: this.autogeneratedNumber.people,
                fontSize: 188.0,
                fontColor: Colors.white.withOpacity(0.8),
                offline: false),
          ],
        ),
      );
  }
}
