import 'package:hmpaisrn/data/launch.dart';
import 'package:hmpaisrn/data/autogenerated.dart';

class AppDataState {
  final Autogenerated peopleInSpace;
  final Launch nextLaunch;
  final Launch previousLaunch;
  final Launch searchLaunch;

  AppDataState(
      {this.peopleInSpace,
      this.nextLaunch,
      this.previousLaunch,
      this.searchLaunch});

  static AppDataState fromJson(dynamic json) => AppDataState(
      peopleInSpace: Autogenerated.fromJson(json['peopleInSpace']),
      nextLaunch: Launch.fromJson(json['upcomingLaunch']),
      previousLaunch: Launch.fromJson(json['previousLaunch']),
      searchLaunch: Launch.fromJson(json['searchLaunch']));

  AppDataState copyWith(
      {peopleInSpace, nextLaunch, previousLaunch, searchLaunch}) {
    return new AppDataState(
      peopleInSpace: peopleInSpace ?? this.peopleInSpace,
      nextLaunch: nextLaunch ?? this.nextLaunch,
      previousLaunch: previousLaunch ?? this.previousLaunch,
      searchLaunch: searchLaunch ?? this.searchLaunch,
    );
  }
}
