import 'dart:convert';

import 'package:hmpaisrn/data/models/launches.dart';
import 'package:hmpaisrn/data/people/autogenerated.dart';

class AppDataState {
  final Autogenerated peopleInSpace;
  final Launches upcomingLaunch;
  final Launches previousLaunch;
  final Launches searchLaunch;
  final bool loading;

  AppDataState(
      {this.peopleInSpace,
      this.upcomingLaunch,
      this.previousLaunch,
      this.searchLaunch,
      this.loading});

  static AppDataState fromJson(dynamic json) => AppDataState(
      peopleInSpace: Autogenerated.fromJson(json['peopleInSpace']),
      upcomingLaunch: json['upcomingLaunch'] == null
          ? null
          : Launches.fromJson(json['upcomingLaunch']),
      previousLaunch: json['previousLaunch'] == null
          ? null
          : Launches.fromJson(json['previousLaunch']),
      searchLaunch: Launches());

  dynamic toJson() => {
        'peopleInSpace': peopleInSpace == null ? null : peopleInSpace.toJson(),
        'upcomingLaunch':
            upcomingLaunch == null ? null : jsonEncode(upcomingLaunch),
        'previousLaunch':
            previousLaunch == null ? null : jsonEncode(previousLaunch)
      };

  AppDataState copyWith(
      {peopleInSpace, upcomingLaunch, previousLaunch, searchLaunch, loading}) {
    return new AppDataState(
      peopleInSpace: peopleInSpace ?? this.peopleInSpace,
      upcomingLaunch: upcomingLaunch ?? this.upcomingLaunch,
      previousLaunch: previousLaunch ?? this.previousLaunch,
      searchLaunch: searchLaunch ?? this.searchLaunch,
      loading: loading ?? this.loading,
    );
  }
}
