import 'package:flutter/material.dart';
import 'package:redux/redux.dart';                              // new
import 'package:hmpaisrn/models/app_state.dart';              // new
import 'package:hmpaisrn/reducers/app_reducer.dart';
import 'screens/home/index.dart';
import 'package:hmpaisrn/services/peopleinspace.dart';
import 'package:redux_thunk/redux_thunk.dart';
import 'package:flutter_redux/flutter_redux.dart';
import 'actions/fetch_actions.dart';
import 'models/app_state.dart';
import 'models/app_data_state.dart';
import 'data/launch.dart';

void main() => runApp(new MainApp());

class MainApp extends StatelessWidget {
  String title = 'MeSuite';

  final routes = <String, WidgetBuilder>{
    '/Home': (BuildContext context) => new Home(),
    '/List': (BuildContext context) => new Home(),
    '/Detail': (BuildContext context) => new Home()
  };

    //
    // Store is just a class that holds your apps State tree.
    // AppState is something that we will (but haven't yet) established
  final store = new Store<AppState>(                            // new
    appReducer,                                                 // new
    initialState: new AppState(),                               // new
    middleware: [thunkMiddleware],                                             // new
  );

  MainApp() {
    store.dispatch(fetchNextLaunchesAction);
  }

  @override
  Widget build(BuildContext context) {
    return new StoreProvider(store: store, child: new Home(title: title, autogenerated: fetchPost()));
  }
}
