/// Flutter icons Rocket
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Rocket
///      fonts:
///       - asset: fonts/Rocket.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Rocket {
  Rocket._();

  static const _kFontFam = 'Rocket';

  static const IconData rocket = const IconData(0xe801, fontFamily: _kFontFam);
}
