import 'package:flutter/material.dart';
import 'screens/home/index.dart';
import 'package:hmpaisrn/services/peopleinspace.dart';

class Routes {
  final routes = <String, WidgetBuilder>{
    '/Home': (BuildContext context) => new Home()
  };

  Routes () {
    runApp(Home(autogenerated: fetchPost()));
  }
}