import 'package:flutter/material.dart';
import 'package:hmpaisrn/data/autogenerated.dart';

class TextNumber extends StatelessWidget {
  final int autogeneratedNumber;
  final double fontSize;
  final Color fontColor;

    //passing props in react style
  TextNumber({
    this.autogeneratedNumber,
    this.fontSize,
    this.fontColor
  });

  @override
  Widget build(BuildContext context) {
    return new Center(
        child: Container(
          child: new Text(autogeneratedNumber.toString(), style: new TextStyle(fontSize: fontSize, color: fontColor)),
          alignment: AlignmentDirectional(0.0, -0.4),
        )
      );
  }
}