import 'package:flutter/material.dart';
import 'package:hmpaisrn/data/people/people.dart';
import 'package:hmpaisrn/screens/list/list.dart';
import 'package:lottie/lottie.dart';

class TextNumber extends StatelessWidget {
  final int autogeneratedNumber;
  final List<People> people;
  final double fontSize;
  final Color fontColor;
  final bool offline;

  //passing props in react style
  TextNumber(
      {this.autogeneratedNumber,
      this.people,
      this.fontSize,
      this.fontColor,
      this.offline});

  @override
  Widget build(BuildContext context) {
    if (offline) {
      return new Center(
        child: Column(
          mainAxisAlignment: MainAxisAlignment.center,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: <Widget>[
            Lottie.asset('assets/bw_rocket.json', width: 100, height: 100),
            new Text(
              "Loading ...",
              style: new TextStyle(fontSize: fontSize, color: fontColor),
            ),
          ],
        ),
      );
    } else
      return new GestureDetector(
          onTap: () {
            Navigator.push(
                context,
                new MaterialPageRoute(
                    builder: (context) => new ListScreen(people: people)));
          },
          child: new Center(
            child: Container(
              child: new Text(autogeneratedNumber.toString(),
                  style: new TextStyle(fontSize: fontSize, color: fontColor)),
              alignment: AlignmentDirectional(0.0, -0.4),
            ),
          ));
  }
}
